"""Generate docs/decisions/0000-index.md from ADR front-matter — a one-read
status map over the ADR corpus (so "which ADRs are Proposed/Superseded" is a single
read, not 62 greps). Regenerate-or-fail gated by tests/test_adr_index.py.

    python scripts/build_adr_index.py          # regenerate the index
    python scripts/build_adr_index.py --check   # exit 1 if the committed index is stale
"""

from __future__ import annotations

import pathlib
import re
import sys

# Both invocations documented above put scripts/ on sys.path, not the repo root, so
# the sibling import below died with ModuleNotFoundError — including for anyone
# following tests/test_adr_index.py's own "run: python scripts/build_adr_index.py"
# remedy. `make adr-index` never noticed because it uses the -m form.
# Guarded by test_demo_serve_cli_entrypoint.py.
_REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from scripts.check_traceability import (  # noqa: E402 — needs the sys.path bootstrap above
    _FRONTMATTER_RE,
    iter_adr_paths,
    parse_adr_frontmatter,
)

INDEX = pathlib.Path("docs/decisions/0000-index.md")
_H1_RE = re.compile(r"^#\s+(.*)$", re.MULTILINE)
_ID_PREFIX_RE = re.compile(r"^(?:ADR[-\s]?)?\d+\s*[:.–—-]\s*")


def _title(path: pathlib.Path) -> str:
    body = _FRONTMATTER_RE.sub("", path.read_text(encoding="utf-8"), count=1)
    m = _H1_RE.search(body)
    title = m.group(1).strip() if m else path.stem
    return _ID_PREFIX_RE.sub("", title)


def render_index(repo_root: pathlib.Path | None = None) -> str:
    repo_root = repo_root or pathlib.Path.cwd()
    rows = []
    for p in iter_adr_paths(repo_root / "docs/decisions"):
        fm = parse_adr_frontmatter(p)
        fm = fm if isinstance(fm, dict) else {}
        rows.append(
            (
                str(fm.get("id", p.stem)),
                str(fm.get("status", "?")),
                _title(p),
                str(fm.get("superseded_by") or ""),
                p.name,
            )
        )
    rows.sort(key=lambda r: r[0])

    lines = [
        "<!-- GENERATED by scripts/build_adr_index.py — do not edit by hand. -->",
        "# ADR index",
        "",
        f"{len(rows)} decisions. Regenerate with `python scripts/build_adr_index.py`.",
        "",
        "| ID | Status | Title | Superseded by |",
        "|---|---|---|---|",
    ]
    for adr_id, status, title, sb, name in rows:
        lines.append(f"| [{adr_id}]({name}) | {status} | {title} | {sb} |")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    content = render_index()
    if "--check" in argv:
        current = INDEX.read_text(encoding="utf-8") if INDEX.exists() else ""
        if current != content:
            print("ADR index is stale — run: python scripts/build_adr_index.py")
            return 1
        print("ADR index up to date.")
        return 0
    INDEX.write_text(content, encoding="utf-8")
    print(f"wrote {INDEX} ({len(content.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
