"""Content-digest gate for the VENDORED codex-security plugin (ADR-0098).

Why this gate exists, stated plainly: the control it replaces never worked.

The ``security-scan-codex`` lane used to claim a "pinned + digest-verified" plugin
install. It asserted that a directory named ``bd2122cb`` existed under the codex plugin
cache. ``bd2122cb`` is not a content digest — it is a *git commit SHA of
openai/plugins*, used by the codex CLI as a cache DIRECTORY NAME, and it is shared
identically by every plugin from that marketplace revision (``codex-security/bd2122cb``,
``google-calendar/bd2122cb``, ``slack/bd2122cb``). The assertion could not distinguish
codex-security from any other plugin, let alone detect a byte changing inside it. It
verified nothing about content. It also never ran: the lane failed 68 times out of 68
in the install step, so the assertion was never even reached.

The plugin is now VENDORED into ``third_party/codex-plugins`` (see the README there for
upstream origin and the exact commit), so the pin is a commit in THIS repository that a
reviewer can diff. This gate is the assertion that replaces the bogus one, and unlike
its predecessor it is about content:

  * every vendored file is hashed (sha256), and the sorted per-file manifest is itself
    hashed into one aggregate tree digest;
  * a changed byte, an added file, a removed file, a new executable bit or a symlink all
    move the aggregate and fail the gate;
  * the same code runs over the tree the codex CLI actually INSTALLED in CI
    (``--tree``), so "what got installed" is checked against "what was audited", not
    against a directory name.

Two callers, one implementation:

    python -m scripts.check_vendored_plugin              # merge ritual: the repo tree
    python -m scripts.check_vendored_plugin --tree DIR   # CI: the installed cache copy
    python -m scripts.check_vendored_plugin --expect HEX  # also require this aggregate
    python -m scripts.check_vendored_plugin --print       # print the computed manifest

``--update`` is deliberately NOT offered. Refreshing the vendored plugin is a review
event, not a command: bump the tree, regenerate the manifest with ``--print``, and say
in the PR which upstream commit you moved to and what the diff contains.

Refs: ADR-0098
"""

from __future__ import annotations

import argparse
import hashlib
import pathlib
import sys

VENDOR_ROOT = pathlib.Path("third_party/codex-plugins")
PLUGIN_DIR = VENDOR_ROOT / "plugins/codex-security"
MANIFEST_PATH = VENDOR_ROOT / "codex-security.sha256"

# Python bytecode caches are generated by RUNNING the plugin, never vendored. They are
# not excluded from the digest — excluding a path is a hole an attacker can hide in.
# They are REJECTED instead: the CI check runs immediately after install and before the
# scan, so at check time no bytecode may exist in either tree.
_BYTECODE_DIR = "__pycache__"
_BYTECODE_SUFFIXES = (".pyc", ".pyo")


def _is_bytecode(rel: str) -> bool:
    return any(
        part == _BYTECODE_DIR or part.endswith(_BYTECODE_SUFFIXES) for part in rel.split("/")
    )


def _hash_file(path: pathlib.Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def manifest_lines(tree: pathlib.Path) -> list[str]:
    """``<sha256>  <relpath>`` for every file under ``tree``, sorted by path.

    Raises ValueError on anything that is not a plain, non-executable regular file, or
    on leftover Python bytecode. A vendored third-party tree that grows a symlink or an
    executable bit is a supply-chain event, so it must fail the gate rather than be
    silently folded into a new digest.
    """
    entries = sorted((path.relative_to(tree).as_posix(), path) for path in tree.rglob("*"))
    lines: list[str] = []
    for rel, path in entries:
        if _is_bytecode(rel):
            raise ValueError(
                f"python bytecode inside the vendored tree: {rel}. Bytecode is generated "
                "by running the plugin and must never be vendored or hashed; remove it "
                "(and, in CI, run this check before the scan, not after)."
            )
        if path.is_symlink():
            raise ValueError(f"symlink inside the vendored tree: {rel}")
        if path.is_dir():
            continue
        if not path.is_file():
            raise ValueError(f"not a regular file inside the vendored tree: {rel}")
        if path.stat().st_mode & 0o111:
            raise ValueError(
                f"executable bit set inside the vendored tree: {rel} (upstream ships "
                "every file mode 100644; an executable is a supply-chain event)"
            )
        lines.append(f"{_hash_file(path)}  {rel}")
    if not lines:
        raise ValueError(f"no files found under {tree} — the vendored tree is missing")
    return lines


def manifest_text(tree: pathlib.Path) -> str:
    return "".join(f"{line}\n" for line in manifest_lines(tree))


def aggregate(text: str) -> str:
    """The tree digest: sha256 over the per-file manifest text."""
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _diff(expected: str, actual: str) -> list[str]:
    """Human-readable per-file differences between two manifest texts."""

    def parse(text: str) -> dict[str, str]:
        out: dict[str, str] = {}
        for line in text.splitlines():
            if line.strip():
                digest, _, rel = line.partition("  ")
                out[rel] = digest
        return out

    want, have = parse(expected), parse(actual)
    notes = [f"  removed: {rel}" for rel in sorted(set(want) - set(have))]
    notes += [f"  added:   {rel}" for rel in sorted(set(have) - set(want))]
    notes += [
        f"  changed: {rel} ({want[rel][:12]} -> {have[rel][:12]})"
        for rel in sorted(set(want) & set(have))
        if want[rel] != have[rel]
    ]
    return notes


def check(
    tree: pathlib.Path,
    manifest_path: pathlib.Path,
    expect: str | None = None,
) -> tuple[int, list[str]]:
    """Return (exit code, output lines). Non-zero on ANY divergence."""
    out: list[str] = []
    if not tree.is_dir():
        return 1, [f"[HARD] vendored plugin tree not found: {tree}"]
    if not manifest_path.is_file():
        return 1, [
            f"[HARD] digest manifest not found: {manifest_path}. Regenerate it with "
            "`python -m scripts.check_vendored_plugin --print`."
        ]

    try:
        actual = manifest_text(tree)
    except ValueError as exc:
        return 1, [f"[HARD] {exc}"]

    recorded = manifest_path.read_text(encoding="utf-8")
    got, want = aggregate(actual), aggregate(recorded)

    if actual != recorded:
        out.append(
            f"[HARD] vendored codex-security content does not match {manifest_path}:\n"
            f"  recorded tree digest {want[:12]}, computed {got[:12]} over {tree}"
        )
        out.extend(_diff(recorded, actual))
        out.append(
            "  If this is a deliberate upstream refresh: update "
            f"{VENDOR_ROOT}/README.md with the new openai/plugins commit, regenerate "
            "the manifest with --print, and say in the PR what the diff contains."
        )
        return 1, out

    if expect is not None and got != expect:
        return 1, [
            f"[HARD] tree digest {got[:12]} does not match the pinned digest "
            f"{expect[:12]} the caller required. The vendored tree and its manifest "
            "agree with each other but not with the pin, so one of them moved without "
            "the other."
        ]

    out.append(f"vendored codex-security verified: tree digest {got[:12]} over {tree}")
    return 0, out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__ or "")
    parser.add_argument(
        "--tree",
        type=pathlib.Path,
        default=None,
        help="directory to verify (default: the vendored tree in this repo). CI passes "
        "the codex plugin cache directory here.",
    )
    parser.add_argument(
        "--expect",
        default=None,
        help="additionally require this aggregate tree digest (the workflow's own pin)",
    )
    parser.add_argument(
        "--print",
        dest="do_print",
        action="store_true",
        help="print the computed per-file manifest, then the aggregate, and exit 0",
    )
    args = parser.parse_args(sys.argv[1:] if argv is None else argv)

    repo_root = pathlib.Path.cwd()
    tree = args.tree if args.tree is not None else repo_root / PLUGIN_DIR

    if args.do_print:
        text = manifest_text(tree)
        sys.stdout.write(text)
        print(f"# tree digest: {aggregate(text)}", file=sys.stderr)
        return 0

    code, lines = check(tree, repo_root / MANIFEST_PATH, expect=args.expect)
    for line in lines:
        print(line)
    return code


if __name__ == "__main__":  # pragma: no cover - CLI entry point
    sys.exit(main())
